export type GraphKind = "topic" | "detail";
export type EdgeKind = "yes" | "no" | "info";

export interface GraphItem {
  id: string;
  label: string;
  kind: GraphKind;
  parentId: string | null;
  tag?: string;
  detail: string;
  /** Pill shown on the incoming edge (the "answer" that revealed this node). */
  edgeLabel?: string;
  edgeKind?: EdgeKind;
}

export const ROOT_ID = "root";

export const GRAPH: GraphItem[] = [
  {
    id: "root",
    label: "Design URL Shortener?",
    kind: "topic",
    parentId: null,
    tag: "HLD",
    detail:
      "A service like bit.ly: long URL in, short alias out. Press + and answer each question — requirements, scale, model, APIs, flows and deep dives reveal themselves as you go.",
  },

  // ── Spine ──────────────────────────────────────────────
  {
    id: "q-do",
    label: "What can users DO?",
    kind: "topic",
    parentId: "root",
    detail: "Start from verbs in the statement. Unfold and interrogate each action with yes / no.",
  },
  {
    id: "q-qual",
    label: "What QUALITY is needed?",
    kind: "topic",
    parentId: "root",
    detail: "Now the adjectives: unique, high-traffic, instant, persistent. Each one hides a constraint.",
  },
  {
    id: "q-scale",
    label: "At WHAT scale?",
    kind: "topic",
    parentId: "root",
    detail: "Numbers drive every choice. Unfold to pin down users, ratios, sizes — then derive storage yourself.",
  },
  {
    id: "q-data",
    label: "What DATA to store?",
    kind: "topic",
    parentId: "root",
    detail: "Nouns become entities. Which nouns survive as tables?",
  },
  {
    id: "q-api",
    label: "What APIs?",
    kind: "topic",
    parentId: "root",
    detail: "One endpoint per user action. Which HTTP verb matches each?",
  },
  {
    id: "q-flow",
    label: "How does TRAFFIC flow?",
    kind: "topic",
    parentId: "root",
    detail: "Write path, read path (the hot one!), analytics path. Unfold each flow.",
  },
  {
    id: "q-id",
    label: "How to mint SHORT IDs?",
    kind: "topic",
    parentId: "root",
    tag: "needs: unique + short",
    detail: "IDs must be globally UNIQUE and SHORT (~5-8 chars). Unfold the options — each expands to when-to-use + tradeoffs.",
  },
  {
    id: "q-enc",
    label: "How to ENCODE the IDs?",
    kind: "topic",
    parentId: "root",
    detail: "Integer → short URL-safe string. Which alphabet wins?",
  },
  {
    id: "q-grow",
    label: "How to SCALE writes?",
    kind: "topic",
    parentId: "root",
    detail: "Handlers scale easily (stateless). The ID generator + DB need sharding so writes stay independent.",
  },

  // ── Functional: verbs → yes/no ─────────────────────────
  {
    id: "q-shorten",
    label: "Shorten a long URL?",
    kind: "topic",
    parentId: "q-do",
    detail: "'Takes a long URL and generates a shorter alias' — is that a core action?",
  },
  {
    id: "a-shorten",
    label: "POST /api/urls/shorten",
    kind: "detail",
    parentId: "q-shorten",
    tag: "CREATE",
    edgeLabel: "yes",
    edgeKind: "yes",
    detail: "YES → CREATE. Accepts longUrl, returns a compact alias (letters + digits), persists the mapping.",
  },
  {
    id: "q-open",
    label: "Open a short link?",
    kind: "topic",
    parentId: "q-do",
    detail: "'Redirects users to the original URL' — core action?",
  },
  {
    id: "a-open",
    label: "GET /{short} → 302",
    kind: "detail",
    parentId: "q-open",
    tag: "READ",
    edgeLabel: "yes",
    edgeKind: "yes",
    detail: "YES → READ, the hot path. Look up the mapping, reply 302 + Location header. Reads will dominate writes.",
  },
  {
    id: "q-track",
    label: "Count clicks?",
    kind: "topic",
    parentId: "q-do",
    detail: "'Track link usage' — do we need it?",
  },
  {
    id: "a-track-yes",
    label: "Async click counter",
    kind: "detail",
    parentId: "q-track",
    tag: "UPDATE",
    edgeLabel: "yes",
    edgeKind: "yes",
    detail: "YES → UPDATE via events, kept off the redirect path so counting never slows a redirect.",
  },
  {
    id: "a-track-no",
    label: "Out of scope",
    kind: "detail",
    parentId: "q-track",
    edgeLabel: "no",
    edgeKind: "no",
    detail: "NO → skip analytics, but keep the hook: the redirect handler can emit events later without redesign.",
  },

  // ── Non-functional: adjectives → yes/no ────────────────
  {
    id: "q-instant",
    label: "Must it feel instant?",
    kind: "topic",
    parentId: "q-qual",
    detail: "'Near real-time', 'efficiently' — is latency a constraint?",
  },
  {
    id: "a-latency",
    label: "Low latency",
    kind: "detail",
    parentId: "q-instant",
    edgeLabel: "yes",
    edgeKind: "yes",
    detail: "YES → single-digit-ms redirects. Read-through cache (Redis) in front of the DB absorbs the read fan-out.",
  },
  {
    id: "q-busy",
    label: "Up under high traffic?",
    kind: "topic",
    parentId: "q-qual",
    detail: "'Handle high traffic' — must it stay reachable 24/7?",
  },
  {
    id: "a-avail",
    label: "High availability",
    kind: "detail",
    parentId: "q-busy",
    edgeLabel: "yes",
    edgeKind: "yes",
    detail: "YES → stateless services behind a load balancer, replicated store. No single point of failure on the read path.",
  },
  {
    id: "q-keep",
    label: "Links live for years?",
    kind: "topic",
    parentId: "q-qual",
    detail: "'Persistent' — do mappings survive failures and time?",
  },
  {
    id: "a-dur",
    label: "Durability",
    kind: "detail",
    parentId: "q-keep",
    edgeLabel: "yes",
    edgeKind: "yes",
    detail: "YES → every mapping persisted in a replicated NoSQL store (DynamoDB / Cassandra).",
  },
  {
    id: "q-one",
    label: "One short → one long?",
    kind: "topic",
    parentId: "q-qual",
    detail: "'Unique alias' — is global uniqueness required?",
  },
  {
    id: "a-uniq",
    label: "Global uniqueness",
    kind: "detail",
    parentId: "q-one",
    edgeLabel: "yes",
    edgeKind: "yes",
    detail: "YES → each short URL maps to exactly one original, across all users. This rules out naive random IDs.",
  },

  // ── Scale: questions → number pills ────────────────────
  {
    id: "q-users",
    label: "Daily users?",
    kind: "topic",
    parentId: "q-scale",
    detail: "How many people use it per day?",
  },
  {
    id: "a-users",
    label: "100M DAU",
    kind: "detail",
    parentId: "q-users",
    edgeLabel: "100M",
    edgeKind: "info",
    detail: "Assume 100M daily active users. Everything below is sized from this.",
  },
  {
    id: "q-rw",
    label: "Reads per write?",
    kind: "topic",
    parentId: "q-scale",
    detail: "Links are opened far more than created. What ratio?",
  },
  {
    id: "a-rw",
    label: "100 : 1",
    kind: "detail",
    parentId: "q-rw",
    edgeLabel: "100:1",
    edgeKind: "info",
    detail: "100 reads per write. Consequence: optimise the read path (cache); the write path can stay simple.",
  },
  {
    id: "q-writes",
    label: "New URLs per day?",
    kind: "topic",
    parentId: "q-scale",
    detail: "How many fresh short links daily?",
  },
  {
    id: "a-writes",
    label: "≈1M writes / day",
    kind: "detail",
    parentId: "q-writes",
    edgeLabel: "1M/day",
    edgeKind: "info",
    detail: "About 1M new mappings a day (~12/s average). Trivial for one box — scale pain lives on the read side.",
  },
  {
    id: "q-bytes",
    label: "Size of one entry?",
    kind: "topic",
    parentId: "q-scale",
    detail: "Short code + long URL + timestamps — how big?",
  },
  {
    id: "a-bytes",
    label: "≈500 bytes",
    kind: "detail",
    parentId: "q-bytes",
    edgeLabel: "500B",
    edgeKind: "info",
    detail: "Roughly 500 bytes per mapping. Multiply it out in the next node.",
  },
  {
    id: "q-ret",
    label: "Keep for how long?",
    kind: "topic",
    parentId: "q-scale",
    detail: "Links shouldn't rot. Retention?",
  },
  {
    id: "a-ret",
    label: "5 years",
    kind: "detail",
    parentId: "q-ret",
    edgeLabel: "5yr",
    edgeKind: "info",
    detail: "5-year retention. Now combine: 1M × 500B × 365 × 5 — open the next node for the answer.",
  },
  {
    id: "q-store",
    label: "Total storage?",
    kind: "topic",
    parentId: "q-scale",
    detail: "Do the math: 1M/day × 500B × 365 days × 5 years = ?",
  },
  {
    id: "a-store",
    label: "≈ 1 TB",
    kind: "detail",
    parentId: "q-store",
    edgeLabel: "≈1TB",
    edgeKind: "info",
    detail: "≈ 0.9 TB plus replication overhead. Fits comfortably in a partitioned NoSQL store — no exotic hardware needed.",
  },

  // ── Data model ─────────────────────────────────────────
  {
    id: "q-map",
    label: "Store short → long?",
    kind: "topic",
    parentId: "q-data",
    detail: "The nouns 'URL' and 'alias' suggest an entity. Keep it?",
  },
  {
    id: "a-map",
    label: "URLMapping table",
    kind: "detail",
    parentId: "q-map",
    edgeLabel: "yes",
    edgeKind: "yes",
    detail: "YES → URLMapping(short_url PK, original_url, created_at). Owned by the Shortening Service so ID generation stays unique.",
  },
  {
    id: "q-clicks",
    label: "Store per-link counts?",
    kind: "topic",
    parentId: "q-data",
    detail: "The noun 'link usage' suggests a second entity. Keep it?",
  },
  {
    id: "a-clicks",
    label: "Analytics table",
    kind: "detail",
    parentId: "q-clicks",
    edgeLabel: "yes",
    edgeKind: "yes",
    detail: "YES → Analytics(short_url, click_count), 1:1 optional with URLMapping. Owned by the Analytics Service; buffered in memory, flushed to DB.",
  },

  // ── APIs ───────────────────────────────────────────────
  {
    id: "q-create",
    label: "An action that CREATES?",
    kind: "topic",
    parentId: "q-api",
    detail: "Shortening creates a resource. Which verb + path?",
  },
  {
    id: "a-post",
    label: "POST /api/urls/shorten",
    kind: "detail",
    parentId: "q-create",
    edgeLabel: "yes",
    edgeKind: "yes",
    detail: "YES → POST with { longUrl }, returns { shortUrl }. Validates, dedups, generates + encodes the ID, persists.",
  },
  {
    id: "q-read",
    label: "An action that READS?",
    kind: "topic",
    parentId: "q-api",
    detail: "Opening a link reads a resource. Which verb + path?",
  },
  {
    id: "a-get",
    label: "GET /api/urls/{short}",
    kind: "detail",
    parentId: "q-read",
    edgeLabel: "yes",
    edgeKind: "yes",
    detail: "YES → GET returns 302 + Location. Emits an async click event — no blocking write on the hot path.",
  },
  {
    id: "q-write-api",
    label: "Public API for analytics?",
    kind: "topic",
    parentId: "q-api",
    detail: "Does the client ever call analytics directly?",
  },
  {
    id: "a-noapi",
    label: "No — internal event",
    kind: "detail",
    parentId: "q-write-api",
    edgeLabel: "no",
    edgeKind: "no",
    detail: "NO → analytics is an internal event stream, not a public endpoint. Keeps the API surface to two calls.",
  },

  // ── HLD flows ──────────────────────────────────────────
  {
    id: "f-short",
    label: "Shortening flow?",
    kind: "topic",
    parentId: "q-flow",
    detail: "The write path: ~12/s average. What boxes does a POST cross?",
  },
  {
    id: "hs-service",
    label: "Shortening Service",
    kind: "detail",
    parentId: "f-short",
    detail: "Generates the unique alias, checks uniqueness, writes the mapping, returns the short URL. Stateless → scales behind a load balancer.",
  },
  {
    id: "hs-db",
    label: "Mapping store",
    kind: "detail",
    parentId: "f-short",
    tag: "DynamoDB / Cassandra",
    detail: "Highly available KV store for short→long rows. Partitioned by shard key (machine prefix — see scaling).",
  },
  {
    id: "f-redir",
    label: "Redirection flow?",
    kind: "topic",
    parentId: "q-flow",
    detail: "The read path — 100x the writes. Where does a GET go first?",
  },
  {
    id: "hr-gateway",
    label: "API Gateway",
    kind: "detail",
    parentId: "f-redir",
    detail: "Single entry: POST → Shortening Service, GET → Redirection Handler (+ fan-out to Analytics).",
  },
  {
    id: "hr-handler",
    label: "Redirection Handler",
    kind: "detail",
    parentId: "f-redir",
    detail: "Looks up the short URL via the cache layer, replies 302 + Location. Never blocks on analytics writes.",
  },
  {
    id: "hr-cache",
    label: "Read-through cache",
    kind: "detail",
    parentId: "f-redir",
    tag: "Redis",
    detail: "Hot mappings in memory. On miss the cache layer loads from DB transparently. Shardable by the same prefix key if needed.",
  },
  {
    id: "f-anal",
    label: "Analytics flow?",
    kind: "topic",
    parentId: "q-flow",
    detail: "Count clicks in real time without slowing redirects. How?",
  },
  {
    id: "an-service",
    label: "Analytics Service",
    kind: "detail",
    parentId: "f-anal",
    detail: "Consumes access events, increments per-URL counters in Redis, flushes to the main DB on a schedule.",
  },
  {
    id: "an-flush",
    label: "Counter flush",
    kind: "detail",
    parentId: "f-anal",
    detail: "Speed of memory + durability of disk: serve real-time counts from Redis, persist batches so failures lose seconds, not history.",
  },

  // ── Deep dive: ID generation ───────────────────────────
  {
    id: "id-hash",
    label: "Hash the long URL?",
    kind: "topic",
    parentId: "q-id",
    detail: "Option 1: Hash(longUrl), e.g. MD5/SHA, truncate to ~7 chars. Deterministic — same URL, same short link. Expand for verdict.",
  },
  {
    id: "id-hash-use",
    label: "When to use",
    kind: "detail",
    parentId: "id-hash",
    detail: "USE when you want dedup for free (same input collapses) and no coordinator. AVOID when collision-retry cost matters at scale.",
  },
  {
    id: "id-hash-trade",
    label: "Tradeoffs",
    kind: "detail",
    parentId: "id-hash",
    detail: "PRO: simple, stateless, no coordination.\nCON: collisions inevitable when truncating → DB check + retry-with-salt loop; extra writes per collision.",
  },
  {
    id: "id-uuid",
    label: "Random UUID?",
    kind: "topic",
    parentId: "q-id",
    detail: "Option 2: 128-bit random UUID per URL. Unique with zero coordination — but 36 chars. Expand for verdict.",
  },
  {
    id: "id-uuid-use",
    label: "When to use",
    kind: "detail",
    parentId: "id-uuid",
    detail: "USE for internal keys needing zero coordination. AVOID as the public short code — too long, unorderable.",
  },
  {
    id: "id-uuid-trade",
    label: "Tradeoffs",
    kind: "detail",
    parentId: "id-uuid",
    detail: "PRO: no single point of failure, negligible collision at full width.\nCON: truncating to 7 chars reintroduces collisions; random → poor locality/indexing.",
  },
  {
    id: "id-snowflake",
    label: "Snowflake IDs?",
    kind: "topic",
    parentId: "q-id",
    detail: "Option 3: Twitter-style 64-bit (timestamp + machine + sequence). Roughly ordered, sortable. Expand for verdict.",
  },
  {
    id: "id-snowflake-use",
    label: "When to use",
    kind: "detail",
    parentId: "id-snowflake",
    detail: "USE when ordering/debuggability matters and you can run a coordinator + NTP. AVOID if you want zero-ops simplicity.",
  },
  {
    id: "id-snowflake-trade",
    label: "Tradeoffs",
    kind: "detail",
    parentId: "id-snowflake",
    detail: "PRO: unique, sortable, high throughput.\nCON: clock-skew risk, machine-ID assignment overhead, still needs encoding to look short.",
  },
  {
    id: "id-machine",
    label: "Machine ID + Seq ★",
    kind: "topic",
    parentId: "q-id",
    tag: "chosen",
    detail: "Option 4, CHOSEN: 1-char machine prefix + per-machine sequence. The prefix doubles as the DB shard key. Expand for why it wins.",
  },
  {
    id: "id-machine-use",
    label: "When to use",
    kind: "detail",
    parentId: "id-machine",
    detail: "USE when write paths must be independent and concurrent — each machine writes only its own shard. Scale by adding machines.",
  },
  {
    id: "id-machine-trade",
    label: "Tradeoffs",
    kind: "detail",
    parentId: "id-machine",
    detail: "PRO: short, guaranteed unique via prefix, shard key for free, zero collision retries.\nCON: needs machine-ID assignment + per-machine seq persistence; skewed machines can hot-spot a shard.",
  },

  // ── Deep dive: encoding ────────────────────────────────
  {
    id: "enc-base16",
    label: "Base16 (hex)?",
    kind: "detail",
    parentId: "q-enc",
    detail: "0-9a-f only. Simple + debuggable but longest: 7 hex chars ≈ 268M space — too small, needs more chars for our scale.",
  },
  {
    id: "enc-base64",
    label: "Base64?",
    kind: "detail",
    parentId: "q-enc",
    detail: "Shortest per char (64 symbols) but +/= break URLs and confuse users. Needs a URL-safe variant — extra complexity for little gain.",
  },
  {
    id: "enc-base62",
    label: "Base62 ★ chosen",
    kind: "detail",
    parentId: "q-enc",
    tag: "chosen",
    detail: "0-9A-Za-z: URL-safe, unambiguous, compact. 62^7 ≈ 3.5T space — 7 chars serve us for years. Pairs with the MachineID+Seq integer.",
  },

  // ── Deep dive: scaling ─────────────────────────────────
  {
    id: "scale-shardkey",
    label: "Prefix as shard key?",
    kind: "detail",
    parentId: "q-grow",
    detail: "YES → machine prefix (first char) routes generation AND storage: short a82c7w lives on shard 'a'. Add a machine → add a shard, zero reconfig.",
  },
  {
    id: "scale-readpath",
    label: "Read routing + cache?",
    kind: "detail",
    parentId: "q-grow",
    detail: "On cache miss the prefix finds the right shard directly — no scatter-gather. Cache itself can shard on the same key later. Hot URLs stay in Redis.",
  },
  {
    id: "scale-pregen",
    label: "Pre-generate IDs?",
    kind: "detail",
    parentId: "q-grow",
    detail: "Optional: mint batches via cron to smooth spikes. Usually unnecessary here — the prefix design already gives independent, contention-free writers.",
  },
];
